### ISSUE TITLE
Reducing duplicate CSS

### ISSUE THREAD

**Issue by jim-rosales** [10tagnew/prj-rev-bwfs-dasmoto#5]
In your three sections brush, frame, and paint you have some similar styles:
```CSS
font-family: Helvetica;
font-size: 32px;
font-weight: bold;
color: white;
```
When you have similar CSS in multiple sections like above, it is best to reduce writing duplicate CSS. For example, here you can do the following:
```CSS
h2 {
  /* font-family: Helvetica;  Better approach shown below */
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
This way all your h2s inherit the CSS above and you only need to apply the unique background color they all have individually. 

As well as multiple sections use the font Helvetica it's more efficient to apply it in the following way:
```CSS
p,
h1,
h2 {
  font-family: Helvetica, serif; /* It's best practice to also provide a fallback font */
}
```
https://github.com/10tagnew/prj-rev-bwfs-dasmoto/blob/9392fd3c0beea2fcd8666c3eb2f70586caeafef2/Dasmoto/style.css#L11-L36
